# CSGOJ judge2 评测机基础镜像
FROM ubuntu:24.04

# 设置环境变量
ENV DEBIAN_FRONTEND=noninteractive
ENV PYTHONUNBUFFERED=1
ENV LANG=zh_CN.UTF-8
ENV LANGUAGE=zh_CN:zh
ENV LC_ALL=zh_CN.UTF-8

# 替换为国内镜像源
RUN sed -i 's/archive.ubuntu.com/mirrors.aliyun.com/g' /etc/apt/sources.list.d/ubuntu.sources && \
    sed -i 's/security.ubuntu.com/mirrors.aliyun.com/g' /etc/apt/sources.list.d/ubuntu.sources

# 安装基础依赖
RUN DEBIAN_FRONTEND=noninteractive apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get -y install --no-install-recommends \
    python3 \
    python3-pip \
    python3-dev \
    gcc \
    g++ \
    gdb \
    make \
    cmake \
    git \
    curl \
    wget \
    tar \
    gzip \
    unzip \
    vim \
    nano \
    htop \
    procps \
    net-tools \
    iputils-ping \
    && rm -rf /var/lib/apt/lists/*


RUN pip3 config set global.index-url https://mirrors.aliyun.com/pypi/simple/

# 安装 Python 依赖
RUN pip3 install --no-cache-dir --break-system-packages \
    tqdm \
    requests 

# 安装编程语言支持和系统依赖
RUN DEBIAN_FRONTEND=noninteractive apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get -y install --no-install-recommends \
    openjdk-17-jdk \
    python3 \
    nodejs \
    npm \
    golang-go \
    php \
    libseccomp-dev \
    python3-seccomp \
    && rm -rf /var/lib/apt/lists/*

# 安装中文语言包
RUN DEBIAN_FRONTEND=noninteractive apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get -y install --no-install-recommends \
    locales \
    locales-all \
    && rm -rf /var/lib/apt/lists/*

# 生成中文语言包
RUN locale-gen zh_CN.UTF-8 && \
    dpkg-reconfigure locales && \
    /usr/sbin/update-locale LANG=zh_CN.UTF-8

# 设置工作目录
WORKDIR /usr/local/bin

CMD ["/bin/bash"]
